server:
  port: 8080
  
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: repair-service
          uri: lb://repair-service
          predicates:
            - Path=/api/v1/repair/**, /api/v1/operation/**
        - id: repair-list-service
          uri: lb://repair-list-service
          predicates:
            - Path=/api/v1/repairList/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/v1/vehicle/**
        - id: bonus-service
          uri: lb://bonus-service
          predicates:
            - Path=/api/v1/bonus/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/v1/report1/**, /api/v1/report2/**