apiVersion: apps/v1
kind: Deployment
metadata:
  name: repair-deployment
  labels:
    app: repair-deployment
spec:
  selector:
    matchLabels:
      app: repair-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: repair-deployment
    spec:
      containers:
        - name: repair
          image: irictm/lab2-tingeso-repair-service
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPAIR
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPAIR
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REPAIR
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPAIR
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPAIR
