apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-deployment
  labels:
    app: vehicle-deployment
spec:
  selector:
    matchLabels:
      app: vehicle-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicle-deployment
    spec:
      containers:
        - name: vehicle
          image: irictm/lab2-tingeso-vehicle-service
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_VEHICLE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_VEHICLE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_VEHICLE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_VEHICLE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_VEHICLE
